### ISSUE TITLE
No Mountable Filesystem

### ISSUE THREAD

**Issue by zlunchbox** [zed-industries/feedback#422] opened 2022-08-05 13:15 UTC
### Check for existing issues

- [X] Completed

### Describe the bug

Both auto update and attempting to open the *.dmg from a manual download of the 0.50.0 release are failing with a message of "No mountable filesystems".

### To reproduce

**Auto Update**

1. Open Zed.log in Console
2. Trigger an auto update in Zed from Zed > Check for Updates
3. Observe Zed successfully download the update then fail after this step with the "error:failed to mount" message

**Manual Download**

1. Manually download Zed 0.50.0 from zed.dev
2. Once downloaded, double-click the *.dmg to open
3. Observe an error dialog that states, "no mountable file systems"

### Expected behavior

Zed successfully auto updates, or a manual download can be successfully mounted and opened.

### Environment

Zed 0.47.1 – /Applications/Zed.app 
macOS 11.6.7 
architecture x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

[Zed.log](https://github.com/zed-industries/feedback/files/9268933/Zed.log)

**Comment by iamnbutler** [comment] 2022-08-05 15:37
Interesting, I just tried this and had no issues opening the dmg (downloading from the site.) Can someone else try this and repro?

**Comment by iamnbutler** [comment] 2022-08-08 16:21
We had a few people try to reproduce this in a variety of environments and can't reproduce so far. Is there any other info you can provide?

**Comment by zlunchbox** [comment] 2022-08-08 18:15
Only other info is that auto update now works as expected! This is after updating to macOS 11.6.8 (where previously I was on 11.6.7). Unsure if the behavior was resolved from simply restarting the machine (which I should've tried before...) or from the upgrade.

**Comment by mikayla-maki** [comment] 2022-08-08 18:26
Thanks for the update @zlunchbox! Since none of us have been able to reproduce this anymore, I think I'm going to close this for now.

**Closed by mikayla-maki** 2022-08-08 18:26 UTC
Labels: panic / crash, discussed, can't reproduce

**Comment by rafavelar** [comment] 2023-08-01 05:25
Hey there, I have that issue with version Zed 0.96.4
<img width="395" alt="Screen Shot 2023-07-31 at 23 25 18" src="https://github.com/zed-industries/community/assets/19939271/1163c447-4a98-4056-8f03-09fb1a045d98">
