### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by sufiyanyusuf** [zed-industries/feedback#421] opened 2022-08-05 12:32 UTC
### Check for existing issues

- [X] Completed

### Describe the bug

App crashes on launch (I have to force quit most of the times)

### To reproduce

Mount the dmg, launch the app 
Note:
I had 0.49 installed, once it crashed due to some bug, and after that I was unable to launch it ever. 
- I tried deleting the cache in Library folder, and also on launching, selecting the option "Don't reopen windows"
- I tried running the app from the mounted vol, as well as from applications folder

### Expected behavior

The app should launch

### Environment

Zed 0.50.0 – /Applications/Zed.app 
macOS 12.5 
architecture arm64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

[Zed.log](https://github.com/zed-industries/feedback/files/9268603/Zed.log)

**Comment by maxbrunsfeld** [comment] 2022-08-05 16:08
Do you have any configuration in `~/.config/zed/settings.json`, or in the old settings location, `~/.zed/settings.json`?

**Comment by sufiyanyusuf** [comment] 2022-08-05 16:10
Yes, both files have the same contents:
`{
    "buffer_font_family": "Iosevka"
}
`

**Comment by maxbrunsfeld** [comment] 2022-08-05 16:11
Ah ok. If you remove that config setting, does the problem go away? I think we have another issue for problems caused by loading very large fonts like Iosevka.

**Comment by sufiyanyusuf** [comment] 2022-08-05 16:13
Yes, it works now. Thanks for your  help!

**Comment by maxbrunsfeld** [comment] 2022-08-05 16:14
Ok, I'll close this out in favor of that other issue. Sorry for the really bad experience there. We'll give an update on that issue when we are able to address that problem.

**Closed by maxbrunsfeld** 2022-08-05 16:14 UTC
Labels: defect, panic / crash, triage
