### ISSUE TITLE
Please support throwing a directory from finder to launch Zed with dir

### ISSUE THREAD

**Issue by reduxdj** [zed-industries/feedback#672] opened 2022-11-08 03:52 UTC
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Atom supports launching/opening a project by throwing the directory at it from the Finder window

### Describe the solution you'd like

Love this feature, please add.

**Comment by JosephTLyons** [comment] 2022-11-08 23:50
Hey @reduxdj, I think this is a duplicate of 

- https://github.com/zed-industries/feedback/issues/333

I'm going to close this one in favor of that one, since it has a lot of upvotes on it.  Feel free to upvote that one.

**Closed by JosephTLyons** 2022-11-08 23:50 UTC
Labels: enhancement, triage
